part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARD = _Paths.ONBOARD;
  static const SIGN_IN = _Paths.SIGN_IN;
  static const SIGN_UP = _Paths.SIGN_UP;
  static const VERIFY = _Paths.VERIFY;
  static const LOCATION = _Paths.LOCATION;
  static const MAP = _Paths.MAP;
  static const OTP = _Paths.OTP;
  static const MAP_NEW = _Paths.MAP_NEW;
  static const SHARE_ADDRESS = _Paths.SHARE_ADDRESS;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const PAYMENT_METHODS = _Paths.PAYMENT_METHODS;
  static const HOME_LOCATION = _Paths.HOME_LOCATION;
  static const ADD_NEW_LOCATION = _Paths.ADD_NEW_LOCATION;
  static const SELECT_ADDRESS = _Paths.SELECT_ADDRESS;
  static const PAYMENT_PAGE = _Paths.PAYMENT_PAGE;
  static const ORDER_SUMMARY = _Paths.ORDER_SUMMARY;
  static const CHECKOUT = _Paths.CHECKOUT;
  static const CART = _Paths.CART;
  static const ORDER_SUCESS = _Paths.ORDER_SUCESS;
  static const MERCHANTS = _Paths.MERCHANTS;
  static const ORDERS = _Paths.ORDERS;
  static const MY_PROFILE = _Paths.MY_PROFILE;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const SIGNLE_ITEM = _Paths.SIGNLE_ITEM;
  static const REVIEW = _Paths.REVIEW;
  static const FILTER = _Paths.FILTER;
  static const FIND_BY_CATEGORY = _Paths.FIND_BY_CATEGORY;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const ORDER_TRACK = _Paths.ORDER_TRACK;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const SEARCH = _Paths.SEARCH;
  static const VIEW_ALL = _Paths.VIEW_ALL;
  static const HELP_AND_SUPPORT = _Paths.HELP_AND_SUPPORT;
  static const PROMOTIONS = _Paths.PROMOTIONS;
  static const FEEDBACKS = _Paths.FEEDBACKS;
  static const MY_REWARD = _Paths.MY_REWARD;
  static const SETTINGS = _Paths.SETTINGS;
  static const FAVORITES = _Paths.FAVORITES;
  static const CHAT = _Paths.CHAT;
  static const DELIVERY_INFO = _Paths.DELIVERY_INFO;
  static const ABOUT_US = _Paths.ABOUT_US;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const TNC = _Paths.TNC;
  static const REFUND_POLICY = _Paths.REFUND_POLICY;
  static const VEHICLE_INFO = _Paths.VEHICLE_INFO;
}

abstract class _Paths {
  static const ORDER_SUCESS = '/order_sucess'; // OrderSucess page
  static const MERCHANTS = '/merchants'; // Merchants page
  static const ORDERS = '/orders'; // Orders page
  static const MY_PROFILE = '/my_profile'; // MyProfile page
  static const NOTIFICATION = '/notification'; // Notification page
  static const SIGNLE_ITEM = '/signle_item'; // SignleItem page
  static const REVIEW = '/review'; // Review page
  static const FILTER = '/filter'; // Filter page
  static const FIND_BY_CATEGORY = '/find_by_category'; // FindByCategory page
  static const ORDER_DETAILS = '/order_details'; // OrderDetails page
  static const ORDER_TRACK = '/order_track'; // OrderTrack page
  static const SPLASH = '/splash'; // Splash page
  static const ONBOARD = '/onboard'; // Onboard page
  static const SIGN_IN = '/sign_in'; // SignIn page
  static const SIGN_UP = '/sign_up'; // SignUp page
  static const VERIFY = '/verify'; // Verify page
  static const LOCATION = '/location'; // Location page
  static const OTP = '/otp'; // Otp page
  static const SHARE_ADDRESS = '/share_address'; // ShareAddress page
  static const DASHBOARD = '/dashboard'; // Dashboard page
  static const HOME = '/home'; // Home page
  static const CART = '/cart'; // Cart page
  static const CHECKOUT = '/checkout'; // Checkout page
  static const ADD_NEW_LOCATION = '/add_new_location'; // AddNewLocation page
  static const HOME_LOCATION = '/home_location'; // HomeLocation page
  static const PAYMENT_METHODS = '/payment_methods'; // PaymentMethods page
  static const EDIT_PROFILE = '/edit_profile'; // EditProfile page
  static const SEARCH = '/search'; // Search page
  static const VIEW_ALL = '/view_all'; // ViewAll page
  static const HELP_AND_SUPPORT = '/help_and_support'; // HelpAndSupport page
  static const PROMOTIONS = '/promotions'; // Promotions page
  static const FEEDBACKS = '/feedbacks'; // Feedbacks page
  static const MY_REWARD = '/my_reward'; // MyReward page
  static const SETTINGS = '/settings'; // Settings page
  static const FAVORITES = '/favorites'; // Favorites page
  static const MAP = '/map'; // Favorites page
  static const CHAT = '/chat'; // Chat page
  static const DELIVERY_INFO = '/delivery_info'; // Chat page
  static const ABOUT_US = '/about_us'; // Chat page
  static const PRIVACY_POLICY = '/privacy_policy'; // Chat page
  static const TNC = '/tnc'; // Chat page
  static const REFUND_POLICY = '/refund_policy'; // Chat page
  static const VEHICLE_INFO = '/vehicle_info'; // Chat page
  static const SELECT_ADDRESS = '/select_address'; // Chat page
  static const PAYMENT_PAGE = '/payment_page'; // Chat page
  static const ORDER_SUMMARY = '/order_summary'; // Chat page
  static const MAP_NEW = '/map_new'; // Chat page
}
